# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: SDS 293 - Modelling for Machine Learning
author: Katherine M. Kinnaird
logo: SDS293.png
copyright: "2026"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: sds293-syllabus.tex

# Information about where the book exists on the web
repository:
  url: https://kmkinnaird.github.io/SDS293-Spring2026/intro.html  # Online location of your book
  path_to_book: _build/html # Optional path to your book, relative to the repository root
  branch: main   # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
